### ISSUE TITLE
meta scope should not be styled

### ISSUE THREAD

**Issue by matter123** [vincentfiestada/cold-horizon#2]
On https://github.com/vincentfiestada/cold-horizon/blob/master/themes/cold.json#L143 you style the meta scope as white. This causes inconsitencies as any token plain source token with a meta scope has a different color than a plain source token without a meta scope.
<img width="514" alt="Screen Shot 2019-05-10 at 09 16 12" src="https://user-images.githubusercontent.com/714007/57541702-8205ea80-7304-11e9-8b06-d35ddc16e841.png">

Sublime Text's textmate scope guide says about meta scopes
>meta. Colors
>
>When styling scopes, resist the urge to directly style meta scopes. They are primarily intended to provide contextual information for preferences and plugins. 

https://www.sublimetext.com/docs/3/scope_naming.html#color_schemes

**Comment by vincentfiestada** [comment]
Thanks for pointing this out. I remember having to use them to overcome some limitations of several language extensions, in particular for C, C++, and Go. For example,

![image](https://user-images.githubusercontent.com/5321175/57565329-a1794200-73ee-11e9-8575-fd978310200f.png)

I couldn't colorize non-primitive types in C++ since they're only scoped to `source.cpp`. This and problems with other language extensions caused me to rely a lot on the meta scope, though it was all very ad hoc and not as neat as I would have wanted.

That said, I understand the value of consistency and adhering to conventions. I think this is preferable to tailoring the theme for specific quirks of the language extensions.

For now, I'll be removing all references to the meta scope. Since there are no tests for themes, I can only visually inspect the result but can't guarantee that the theme will look exactly the same.

**Comment by matter123** [comment]
Thanks for removing the references to meta.

I understand it's frustrating about the lack of scoping. Vscode 1.34 is switching tohttps://github.com/jeff-hykin/cpp-textmate-grammar the particular example you provided is being tracked at https://github.com/jeff-hykin/cpp-textmate-grammar/issues/134 , so there should be more scopes soon.

**Comment by vincentfiestada** [comment]
That's good to know. I don't do C++ programming myself but it's nice to know the community is improving on this.
